# code: language=yaml
# roles/network/files/schema.yml
---
# Active Profile
profile: "home"

network:
  # Set to true to use static IP config, false to use DHCP.
  # This value can be overridden in host_vars/<node>.yml
  static: false

  # Optional MTU setting applied to the network interface
  # If undefined, the system default MTU will be used.
  mtu: 1500

  # Define all physical/logical zones in the infrastructure
  zones:
    home:
      profile: "lab"
      fqdn: local
      mtu: 1500
      cidr: "192.168.10.0/24"
      gateway: "192.168.10.1"
      dns: "192.168.10.1"
      bmc: "192.168.10.15"
      nodes:
        node1: "192.168.10.21"
        node2: "192.168.10.22"
        node3: "192.168.10.23"
        node4: "192.168.10.24"
