# code: language=ansible
# roles/k3s/tasks/profiles/production.yml
---
- name: Create directory for Longhorn
  tags: [install, profile, repair]
  become: true
  ansible.builtin.file:
    path: "/data"
    state: directory
    mode: "0775"
    owner: root
    group: root

- name: Create directory for Longhorn
  tags: [install, profile, repair]
  become: true
  ansible.builtin.file:
    path: "{{ k3s.profiles[profile].longhorn.storage_path }}"
    state: directory
    mode: "0775"
    owner: root
    group: root

- name: Create directory for local data
  tags: [install, profile, repair]
  become: true
  ansible.builtin.file:
    path: "/data/local"
    state: directory
    mode: "0775"
    owner: root
    group: root

- name: Tag node with {{ profile }} label
  tags: [install, profile, repair]
  become: true
  become_user: ubuntu
  ignore_errors: true
  ansible.builtin.shell:
    cmd: kubectl label node $(hostname) profile={{ profile }} --overwrite

- name: Tag nodes as workers
  tags: [install, profile, repair]
  become: true
  become_user: ubuntu
  ansible.builtin.shell:
    cmd: kubectl label node $(hostname) node-role.kubernetes.io/worker=worker --overwrite

- name: Configure multipath to blacklist Longhorn devices
  tags: [install, profile, repair]
  become: true
  block:
    - name: Ensure multipath.conf exists
      ansible.builtin.file:
        path: /etc/multipath.conf
        state: touch
        mode: "0644"

    - name: Add blacklist configuration for Longhorn devices
      ansible.builtin.blockinfile:
        path: /etc/multipath.conf
        block: |
          blacklist {
              devnode "^sd[a-z0-9]+"
          }
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Longhorn Multipath Blacklist"
        insertafter: EOF

    - name: Check if myservice exists
      ansible.builtin.shell: |
        systemctl list-unit-files | grep -q '^myservice\.service'
      register: multipathd_exists
      changed_when: false
      failed_when: false

    - name: Restart multipathd service
      when: multipathd_exists.rc == 0
      ansible.builtin.service:
        name: multipathd
        state: restarted
      ignore_errors: true

    - name: Annotate node to disable Longhorn multipath check
      become_user: ubuntu
      ansible.builtin.command: >
        kubectl annotate node {{ inventory_hostname }} longhorn.io/disable-multipath-check=true --overwrite

- name: Disable and mask multipathd service
  tags: [install, profile, repair]
  become: true
  when: multipathd_exists.rc == 0
  ansible.builtin.systemd:
    name: multipathd
    state: stopped
    enabled: false
    masked: true
    daemon_reload: true
