---
collections:
  - name: ansible.netcommon
  - name: ansible.posix
  - name: ansible.utils
  - name: community.crypto
  - name: community.general
  - name: community.docker
  - name: kubernetes.core
