# code: language=yaml
---
tailscale:
  # Enable Tailscale on this host (default: false)
  enabled: false

  # Docker support (default: false)
  # Set to true if you want Tailscale to run in a Docker container
  # This is useful for devices that don't support Tailscale natively
  # Note: This will not work on all devices, especially ARM64
  # Set to false if you want Tailscale to run natively
  # This is the default for most devices
  docker:
    # Enable Docker support (default: false)
    enabled: false

    # Docker data directory (default: /var/lib/docker)
    mount: "/var/lib/tailscale"

  # List of tags to advertise for this device (e.g., ["tag:infra", "tag:gpu"])
  tags: []

  # Enable SSH access to this device (default: false)
  ssh: true

  # Optional prefix to prepend to the hostname (e.g., "node" → "node-host1")
  hostname_prefix: "node"

  # Subnet routes to advertise (e.g., ["192.168.0.0/24"])
  advertise_routes: []

  # Enable subnet routing (usually requires --advertise-routes)
  enable_subnet_router: true

  # Enable MagicDNS (recommended)
  magic_dns: true

  # Accept routes from other nodes (default: true)
  accept_routes: true

  # Optional control server override (enterprise/self-hosted)
  control_server: ""

  # Admin & device API key management
  api:
    device:
      # The device auth key used in `tailscale up` (managed by automation)
      # Generate with tailscale-device-key command
      key: ""

  # Name of the Tailscale network
  tailnet: ""
