# code: language=yaml
---
tailscale:
  # List of tags to advertise for this device (e.g., ["tag:nl", "tag:gpu"])
  tags: []

  # Optional prefix to prepend to the hostname (e.g., "node" → "node-host1")
  hostname_prefix: "node"

  # Subnet routes to advertise (e.g., ["192.168.0.0/21"])
  advertise_routes: []

  # Enable subnet routing (usually requires --advertise-routes)
  enable_subnet_router: false

  # Enable MagicDNS (recommended)
  magic_dns: true

  # Accept routes from other nodes (default: true)
  accept_routes: true

  # Optional control server override (enterprise/self-hosted)
  control_server: ""

  # Admin & device API key management
  api:
    admin:
      # Admin API key used to generate device keys via the Tailscale API
      key: ""
      # The tag to assign to the generated device keys
      tags: ""
      # Key expiry for generated device keys (e.g., "90d")
      expiry: "90d"

    device:
      # The device auth key used in `tailscale up` (managed by automation)
      key: ""
      # Whether this key should be ephemeral
      ephemeral: false
      # Whether this key should be reusable (not recommended)
      reusable: true

  # Name of the Tailscale network
  tailnet: ""
