apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes {{ k3s.profiles[profile].cluster.domain }} in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        template IN AAAA {
          match .* 
          answer {}
        }
        forward . /etc/resolv.conf {
          policy sequential
          max_concurrent 15
        }
        cache 30
        loop
        reload
        loadbalance
    }
