# code: language=ansible
---
- name: Get Version # noqa: command-instead-of-module risky-shell-pipe
  delegate_to: localhost
  tags: [tools, glab]
  ansible.builtin.shell:
    cmd: curl -s "https://gitlab.com/api/v4/projects/34675721/repository/tags" | jq -r '.[0].name'
  register: glab_version_raw
  changed_when: false
  run_once: true

- name: Set Version
  delegate_to: localhost
  tags: [tools, glab]
  ansible.builtin.set_fact:
    glab_version: "{{ glab_version_raw.stdout_lines[0] }}"
  changed_when: false
  run_once: true

- name: Set Version File
  delegate_to: localhost
  tags: [tools, glab]
  ansible.builtin.set_fact:
    glab_version_file: "{{ glab_version_raw.stdout_lines[0] | regex_replace('^v', '') }}"
  changed_when: false
  run_once: true

- name: Manually gather facts on localhost
  tags: [tools, glab]
  delegate_to: localhost
  run_once: true
  ansible.builtin.setup:
  register: localhost_facts

- name: Set OS-specific facts for glab
  tags: [tools, glab]
  delegate_to: localhost
  ansible.builtin.set_fact:
    glab_os: "{{ 'darwin' if localhost_facts.ansible_facts['ansible_system'] == 'Darwin' else 'linux' }}"
    glab_arch: "{{ 'arm64' if localhost_facts.ansible_facts['ansible_architecture'] in ['aarch64', 'arm64'] else 'amd64' }}"
    glab_ext: "{{ 'tar.gz' if localhost_facts.ansible_facts['ansible_system'] == 'Darwin' else 'deb' }}"
  run_once: true

- name: Set OS-specific facts for glab
  tags: [tools, glab]
  delegate_to: localhost
  ansible.builtin.set_fact:
    glab_dest: "/tmp/k9s.{{ glab_ext }}"
  run_once: true

- name: Download glab (DevContainer)
  tags: [tools, glab]
  delegate_to: localhost
  ansible.builtin.get_url:
    url: "https://gitlab.com/gitlab-org/cli/-/releases/{{ glab_version }}/downloads/glab_{{ glab_version_file }}_{{ glab_os }}_{{ glab_arch }}.{{ glab_ext }}"
    dest: "{{ glab_dest }}"
    mode: "0755"
  changed_when: true
  run_once: true

- name: Install glab on Linux (DevContainer)
  when: glab_ext == 'deb'
  delegate_to: localhost
  tags: [tools, glab]
  become: true
  ansible.builtin.command:
    cmd: "dpkg -i {{ glab_dest }}"
  args:
    creates: /usr/local/bin/glab
  changed_when: true
  run_once: true

- name: Extract and install glab on macOS (DevContainer)
  when: glab_ext == 'tar.gz'
  delegate_to: localhost
  tags: [tools, glab]
  become: false
  ansible.builtin.unarchive:
    src: "{{ glab_dest }}"
    dest: "/usr/local/bin/"
    remote_src: true
    mode: "0755"
  args:
    creates: /usr/local/bin/glab
  changed_when: true
  run_once: true
