# code: language=ansible
---
- name: Helm Config
  tags: [helm]
  ansible.builtin.set_fact:
    helm_config: "{{ playbook_dir + '/../' + 'helm.yml' }}"

- name: Load helm.yml
  tags: [helm]
  ansible.builtin.set_fact:
    helm: "{{ lookup('file', helm_config) | from_yaml }}"

- name: Load helm.yml
  delegate_to: localhost
  tags: [helm]
  ansible.builtin.set_fact:
    helm: "{{ lookup('file', helm_config) | from_yaml }}"

- name: Delete (Nodes)
  tags: [helm]
  ansible.builtin.file:
    path: /tmp/get_helm.sh
    state: absent
  run_once: true

- name: Get Helm
  tags: [helm]
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: "0755"
  changed_when: true

- name: Install Helm (Nodes)
  tags: [helm]
  become: true
  ansible.builtin.command:
    cmd: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm
  changed_when: true

- name: Delete (Nodes)
  delegate_to: localhost
  tags: [helm]
  ansible.builtin.file:
    path: /tmp/get_helm.sh
    state: absent
  run_once: true
- name: Add Helm Repositories (Nodes)
  when: >
    helm.repository is defined
    and
    helm.repository | length > 0
  tags: [helm]
  become: true
  become_user: ubuntu
  ansible.builtin.command:
    cmd: "helm repo add {{ item.name }} {{ item.url }}"
  loop: "{{ helm.repository }}"
  changed_when: true

- name: Get Helm (DevContainer)
  tags: [helm]
  delegate_to: localhost
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: "/tmp/get_helm.sh"
    mode: "0755"
  changed_when: true
  run_once: true

- name: Install Helm (DevContainer)
  delegate_to: localhost
  tags: [helm]
  become: true
  ansible.builtin.command:
    cmd: "/tmp/get_helm.sh"
  args:
    creates: /usr/local/bin/helm
  changed_when: true
  run_once: true

- name: Delete (DevContainer)
  delegate_to: localhost
  tags: [helm]
  ansible.builtin.file:
    path: /tmp/get_helm.sh
    state: absent
  run_once: true

- name: Add Helm Repositories (DevContainer)
  delegate_to: localhost
  tags: [helm]
  when: >
    helm.repository is defined
    and
    helm.repository | length > 0
  ansible.builtin.command:
    cmd: "helm repo add {{ item.name }} {{ item.url }}"
  loop: "{{ helm.repository }}"
  changed_when: true
  run_once: true
