# Task known_hosts.yml
#
# IMPORTANT: Run in Serial
#
# Usage:
# - name: Add config
#   vars:
#     host: "{{ user }}"
#     hostname: "{{ bmc_host }}"
#     username: "{{ bmc_user }}"
#     key: "{{ bmc_key }}"
#   ansible.builtin.include_role:
#     name: ssh
#     tasks_from: config.yml
#
---
- name: Delete config
  delegate_to: localhost
  ansible.builtin.raw: |
    TEMP_SED=$(sed '/^Host {{ host }}$/,/^$/d' ~/.ssh/config)
    sudo echo "${TEMP_SED}" > ~/.ssh/config
  changed_when: true

- name: Add config
  delegate_to: localhost
  ansible.builtin.raw: sudo echo "\nHost {{ host }}\n  HostName {{ hostname }}\n  User {{ username }}\n  IdentityFile {{ key }}\n  ServerAliveInterval 60\n" >> ~/.ssh/config
  changed_when: true
