# code: language=ansible
---
# Task known_hosts.yml
#
# IMPORTANT: Run in Serial
#
# Usage:
# - name: Add known_host
#   vars:
#     host: "{{ bmc_host }}"
#   ansible.builtin.include_role:
#     name: ssh
#     tasks_from: known_hosts.yml
#
- name: Remove known_host
  delegate_to: localhost
  ansible.builtin.raw: |
    TEMP_SED=$(sed '/{{ host }}/d' ~/.ssh/known_hosts)
    sudo echo "${TEMP_SED}" > ~/.ssh/known_hosts
  changed_when: true

- name: Get SSH fingerprints
  delegate_to: localhost
  ansible.builtin.raw: ssh-keyscan {{ host }}
  register: ssh_fingerprint
  changed_when: false

- name: Add known_host
  delegate_to: localhost
  when: >
    not item.startswith('#')
    and
    ssh_fingerprint is defined
  ansible.builtin.raw: sudo echo "{{ item }}" >> ~/.ssh/known_hosts
  loop: "{{ ssh_fingerprint.stdout_lines | default('[]') }}"
  changed_when: true

- name: Ensure correct owner
  delegate_to: localhost
  ansible.builtin.raw: "sudo chown vscode:vscode ~/.ssh/known_hosts"
  changed_when: true

- name: Ensure correct file permissions
  delegate_to: localhost
  ansible.builtin.raw: "sudo chmod 0644 ~/.ssh/known_hosts"
  changed_when: true
