---
- name: Set Prefix TPI
  when: inventory_hostname in groups.tpi
  ansible.builtin.set_fact:
    prefix: "{{ hostvars[inventory_hostname]['ansible_ssh_prefix'] }}"

- name: Set Prefix Nodes
  when: inventory_hostname not in groups.tpi
  ansible.builtin.set_fact:
    prefix: "{{ hostvars[hostvars[inventory_hostname]['bmc']]['ansible_ssh_prefix'] }}"

- name: Generate User SSH Keys
  loop:
    - "{{ users.default }}"
    - "{{ users.provision }}"
  loop_control:
    loop_var: user
  ansible.builtin.include_tasks: keys.yml

- name: Set User
  when: inventory_hostname in groups.tpi
  ansible.builtin.set_fact:
    user: "{{ inventory_hostname }}"

- name: Set User
  when: inventory_hostname not in groups.tpi
  ansible.builtin.set_fact:
    user: "{{ hostvars[inventory_hostname]['bmc'] }}"

- name: Generate SSH Keys
  ansible.builtin.include_tasks: keys.yml
