---
- name: Set Prefix TPI
  when: inventory_hostname in groups.tpi
  ansible.builtin.set_fact:
    prefix: "{{ hostvars[inventory_hostname]['ansible_ssh_prefix'] }}"

- name: Set Prefix Nodes
  when: inventory_hostname not in groups.tpi
  ansible.builtin.set_fact:
    prefix: "{{ hostvars[hostvars[inventory_hostname]['bmc']]['ansible_ssh_prefix'] }}"

- name: Generate User SSH Keys
  loop:
    - "{{ users.default }}"
    - "{{ users.provision }}"
  loop_control:
    loop_var: user
  ansible.builtin.include_tasks: keys.yml

- name: Set User
  when: inventory_hostname in groups.tpi
  ansible.builtin.set_fact:
    user: "{{ inventory_hostname }}"

- name: Set User
  when: inventory_hostname not in groups.tpi
  ansible.builtin.set_fact:
    user: "{{ hostvars[inventory_hostname]['bmc'] }}"

- name: Generate SSH Keys
  ansible.builtin.include_tasks: keys.yml

- name: Install BMC SSH Key
  vars:
    prefix: "{{ hostvars[user]['ansible_ssh_prefix'] }}"
    bmc_key: "{{ prefix }}.{{ user }}.key"
    bmc_host: "{{ hostvars[user]['ansible_ssh_host'] }}"
    bmc_user: "{{ hostvars[user]['ansible_ssh_user'] }}"
    bmc_pass: "{{ hostvars[user]['ansible_ssh_pass'] }}"
  ansible.builtin.include_tasks: install.yml
