---
- name: Generate User SSH Keys
  vars:
    prefix: "{{ hostvars[inventory_hostname]['ansible_ssh_prefix'] }}"
  loop:
    - "{{ users.default }}"
    - "{{ users.provision }}"
  loop_control:
    loop_var: user
  ansible.builtin.include_tasks: keys.yml

- name: Generate BMC SSH Keys
  vars:
    prefix: "{{ hostvars[user]['ansible_ssh_prefix'] }}"
    user: "{{ inventory_hostname }}"
  ansible.builtin.include_tasks: keys.yml

- name: Install BMC SSH Key
  vars:
    prefix: "{{ hostvars[user]['ansible_ssh_prefix'] }}"
    user: "{{ inventory_hostname }}"
    bmc_key: "{{ ssh.path }}/{{ prefix }}.{{ user }}.key"
    bmc_host: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
    bmc_user: "{{ hostvars[inventory_hostname]['ansible_ssh_user'] }}"
    bmc_pass: "{{ hostvars[inventory_hostname]['ansible_ssh_pass'] }}"
  ansible.builtin.include_tasks: install.yml
