# code: language=ansible
---
# Configure NFS exports and prepare export directories
- name: Ensure NFS export directories exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop: "{{ nfs.server.exports }}"

- name: Configure /etc/exports from template
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
  notify: "nfs : restart-nfs-server"
