# code: language=ansible
---
# Install NFS server components

- name: Install NFS server packages
  become: true
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Ensure NFS service is enabled and running
  become: true
  ansible.builtin.systemd:
    name: nfs-server
    enabled: true
    state: started
