---
- name: Initialize resolved_ips for export {{ export_item.path }}
  ansible.builtin.set_fact:
    resolved_ips: []

- name: Resolve clients for export {{ export_item.path }}
  ansible.builtin.include_tasks: resolve_single_client.yml
  loop: "{{ export_item.clients }}"
  loop_control:
    loop_var: client_item

- name: Append resolved export for {{ export_item.path }}
  ansible.builtin.set_fact:
    nfs_exports: "{{ nfs_exports + [{'path': export_item.path, 'ips': resolved_ips | unique}] }}"
