# code: language=ansible
---
- name: Configure Network
  tags: [network]
  when: >
    not inventory_hostname in groups['tpi']
    and
    hostvars[inventory_hostname]['type'] | upper == 'RK1'
  ansible.builtin.include_tasks:
    file: netplan.yml

- name: Configure MulticastDNS
  tags: [network]
  when: >
    not inventory_hostname in groups['tpi']
    and
    hostvars[inventory_hostname]['type'] | upper == 'RK1'
  ansible.builtin.template:
    src: mdns.j2
    dest: /etc/systemd/network/10-multicast.network
    owner: root
    group: root
    mode: "0644"
  notify: "network : netplan-apply"
