---
- name: Install-2-NVMe
  when: root_is_mmc
  tags: [rk1]
  become: true
  block:
    - name: Update 'ubuntu-rockchip-settings' # noqa: package-latest
      ansible.builtin.apt:
        name: ubuntu-rockchip-settings
        state: latest
        update_cache: true
        install_recommends: true

    - name: Install
      ansible.builtin.raw: yes | ubuntu-rockchip-install {{ nvme_dev }}
      register: nvme_install
      changed_when: true

    - name: Show Install Result
      ansible.builtin.debug:
        var: nvme_install

    - name: Reboot
      ansible.builtin.reboot:

    - name: Wait on {{ inventory_hostname }}
      delegate_to: localhost
      ansible.builtin.wait_for:
        host: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        port: 22
      retries: 20
      delay: 3
