# code: language=ansible
---
# https://stackoverflow.com/questions/61597724/how-do-i-get-the-root-device-through-ansible
- name: Get Root Device
  tags: [rk1]
  when: hostvars[inventory_hostname]['type'] | upper == "RK1"
  ansible.builtin.raw: df -hT |grep /$|awk '{print $1}'| xargs basename
  register: root_dev_rc
  changed_when: false

- name: Root Device
  tags: [rk1]
  when: hostvars[inventory_hostname]['type'] | upper == "RK1"
  ansible.builtin.set_fact:
    root_dev: "{{ root_dev_rc.stdout_lines[0] | trim | lower }}"

- name: Is MMC
  tags: [rk1]
  when: hostvars[inventory_hostname]['type'] | upper == "RK1"
  ansible.builtin.set_fact:
    root_is_mmc: "{{ root_dev.startswith('mmc') | bool }}"

- name: Target Root Device
  tags: [rk1]
  when: hostvars[inventory_hostname]['type'] | upper == "RK1"
  ansible.builtin.set_fact:
    nvme_dev: "{{ hostvars[inventory_hostname]['root'] }}"

- name: Instal-2-NVMe
  tags: [rk1]
  when: root_is_mmc and nvme_dev is defined
  ansible.builtin.include_tasks:
    file: install.yml
