# roles/tailscale/tasks/main.yml

- name: Assert required Tailscale variables are defined and valid
  ansible.builtin.assert:
    that:
      - tailscale is defined
      - tailscale.authkey is string or tailscale.authkey == ""
      - tailscale.tags is iterable
      - tailscale.hostname_prefix is string
      - tailscale.advertise_routes is iterable
      - tailscale.enable_subnet_router is boolean
      - tailscale.magic_dns is boolean
      - tailscale.accept_routes is boolean
      - tailscale.control_server is string or tailscale.control_server == ""
    fail_msg: "One or more required Tailscale variables are missing or invalid."

- name: Check if Tailscale is already installed
  tags: [setup]
  ansible.builtin.command: which tailscale
  register: tailscale_installed
  ignore_errors: true
  changed_when: false

- name: Install Tailscale
  when: tailscale_installed.rc != 0
  tags: [setup]
  block:
    - name: Get distribution codename
      ansible.builtin.command: lsb_release -cs
      register: distro_codename
      changed_when: false

    - name: Install required dependencies (Ubuntu)
      ansible.builtin.apt:
        name:
          - curl
          - gnupg2
        state: present
        update_cache: true
        cache_valid_time: 3600

    - name: Add Tailscale APT key
      ansible.builtin.apt_key:
        url: https://pkgs.tailscale.com/stable/ubuntu/{{ distro_codename.stdout }}.noarmor.gpg
        state: present

    - name: Add Tailscale APT repository
      ansible.builtin.apt_repository:
        repo: "deb https://pkgs.tailscale.com/stable/ubuntu {{ distro_codename.stdout }} main"
        state: present

    - name: Install Tailscale package
      ansible.builtin.apt:
        name: tailscale
        update_cache: true

- name: Enable and start Tailscale service (no authkey)
  tags: [tailscale]
  ansible.builtin.systemd:
    name: tailscaled
    enabled: true
    state: started

- name: Bring up Tailscale using authkey (if provided)
  when: tailscale.authkey is defined and tailscale.authkey != ""
  tags: [tailscale]
  ansible.builtin.command: >
    tailscale up
    --authkey {{ tailscale.authkey }}
    {% if tailscale.tags %}--advertise-tags={{ tailscale.tags | join(",") }}{% endif %}
    {% if tailscale.advertise_routes %}--advertise-routes={{ tailscale.advertise_routes | join(",") }}{% endif %}
    {% if tailscale.hostname_prefix %}--hostname {{ tailscale.hostname_prefix }}-{{ inventory_hostname }}{% endif %}
    {% if tailscale.magic_dns %}--accept-dns{% endif %}
    {% if tailscale.accept_routes %}--accept-routes{% endif %}
  args:
    creates: /var/lib/tailscale/tailscaled.state
  changed_when: false
