# code: language=ansible
---
- name: Get distribution codename
  ansible.builtin.command: lsb_release -cs
  register: distro_codename
  changed_when: false

- name: Install required dependencies (Ubuntu)
  ansible.builtin.apt:
    name:
      - curl
      - gnupg2
    state: present
    cache_valid_time: 3600

- name: Add Tailscale APT key
  ansible.builtin.apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/{{ distro_codename.stdout }}.noarmor.gpg
    state: present

- name: Add Tailscale APT repository
  ansible.builtin.apt_repository:
    repo: "deb https://pkgs.tailscale.com/stable/ubuntu {{ distro_codename.stdout }} main"
    state: present

- name: Install Tailscale
  ansible.builtin.apt:
    name: tailscale
    update_cache: true

- name: Enable and start Tailscale service
  ansible.builtin.systemd:
    name: tailscaled
    enabled: true
    state: started

- name: Authenticate with Tailscale using authkey (if provided)
  when: tailscale.authkey != ""
  ansible.builtin.shell: >
    tailscale up
    {% if tailscale.authkey %}--authkey {{ tailscale.authkey }}{% endif %}
    {% if tailscale.tags %}--advertise-tags={{ tailscale.tags | join(",") }}{% endif %}
    {% if tailscale.advertise_routes %}--advertise-routes={{ tailscale.advertise_routes | join(",") }}{% endif %}
    {% if tailscale.hostname_prefix %}--hostname {{ tailscale.hostname_prefix }}-{{ inventory_hostname }}{% endif %}
    {% if tailscale.magic_dns %}--accept-dns{% endif %}
    {% if tailscale.accept_routes %} --accept-routes{% endif %}
  args:
    warn: false
  changed_when: true
