#!/usr/bin/env bash
# shellcheck shell=bash

# Prepare SSH directory
if [[ ! -d "${HOME}/.ssh/tpi" ]]; then
    mkdir -p "${HOME}/.ssh/tpi"
fi

# Prepare Data directory
if [[ ! -d "${HOME}/.tpi" ]] && [[ ! -L "${HOME}/.tpi" ]]; then
    mkdir -p "${HOME}/.tpi"
fi

if [[ ! -f "${HOME}/.ssh/.ansible_vault_pass" ]]; then
    touch "${HOME}/.ansible_vault_pass"
fi

if [[ ! -d "${HOME}/.kube" ]]; then
    mkdir -p "${HOME}/.kube"
fi

if [[ ! -f "${HOME}/.kube/config" ]]; then
    touch "${HOME}/.kube/config"
fi
