# code: language=ansible
# roles/k3s/tasks/main.yml
---
- name: Uninstall K3s
  tags: [uninstall]
  when: "'uninstall' in ansible_run_tags"
  ansible.builtin.include_tasks:
    file: uninstall.yml

- name: Merge selected profile into k3s config
  tags: [install]
  ansible.builtin.include_tasks:
    file: shared/config.yml

- name: Merge selected profile into k3s config
  tags: [install]
  ansible.builtin.include_tasks:
    file: shared/token.yml

- name: Helm
  tags: [install, tools, helm]
  ansible.builtin.include_tasks:
    file: tools/helm.yml

# - name: Flux
#   tags: [install, tools, flux]
#   ansible.builtin.include_tasks:
#     file: tools/flux.yml

# - name: Arkade
#   tags: [install, tools, arkade]
#   ansible.builtin.include_tasks:
#     file: tools/arkade.yml

- name: k9s # noqa: name[casing]
  tags: [install, tools, k9s]
  ansible.builtin.include_tasks:
    file: tools/k9s.yml

- name: glab # noqa: name[casing]
  tags: [install, tools, glab]
  ansible.builtin.include_tasks:
    file: tools/glab.yml

- name: Install and configure K3s (shared logic)
  tags: [install]
  ansible.builtin.include_tasks:
    file: shared/k3s.yml

# - name: Patch CoreDNS
#   tags: [install, coredns]
#   ansible.builtin.include_tasks:
#     file: shared/coredns.yml

- name: Deploy kube-vip
  tags: [install, kube-vip]
  ansible.builtin.include_tasks:
    file: shared/kube-vip.yml

- name: Kube Config
  tags: [install, kubeconfig]
  ansible.builtin.include_tasks:
    file: shared/kubeconfig.yml

# - name: Bootstrap Flux
#   when: "'flux-system' in ansible_run_tags"
#   tags: [flux]
#   ansible.builtin.include_tasks:
#     file: shared/flux.yml

- name: Run profile-specific tasks {{ profile }}
  tags: [install, profile]
  ansible.builtin.include_tasks:
    file: "profiles/{{ profile }}.yml"
