# code: language=ansible
# roles/k3s/tasks/main.yml
---
- name: Merge selected profile into k3s config
  ansible.builtin.import_tasks: shared/config.yml

- name: Install and configure K3s (shared logic)
  ansible.builtin.import_tasks: shared/k3s.yml

- name: Deploy Longhorn to {{ k3s.longhorn.storage_path }}
  ansible.builtin.import_tasks: shared/longhorn.yml

- name: Run profile-specific tasks {{ k3s.profile }}
  ansible.builtin.import_tasks: "profiles/{{ k3s.profile }}.yml"

- name: Run post-deploy validations
  ansible.builtin.import_tasks: validate.yml
