---
- name: Uninstall K3s
  tags: [uninstall]
  when: "'uninstall' in ansible_run_tags"
  ansible.builtin.stat:
    path: /usr/local/bin/k3s-uninstall.sh
  register: k3s_uninstall_script

- name: Uninstall K3s
  when: >
    k3s_uninstall_script.stat.exists
    and
    "'uninstall' in ansible_run_tags"
  tags: [uninstall]
  become: true
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s-uninstall.sh
  changed_when: true

- name: Remove K3s config and data directories
  when: >
    k3s_uninstall_script.stat.exists
    and
    "'uninstall' in ansible_run_tags"
  tags: [uninstall]
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ k3s.config_dir }}"
    - "{{ k3s.data_dir }}"
    - /etc/rancher
    - /var/lib/rancher
    - /var/lib/containerd
    - /var/lib/cni
    - /opt/cni
    - /run/k3s
    - /run/containerd
    - /opt/containerd
    - /var/lib/kubelet

- name: Stop
  when: >
    k3s_uninstall_script.stat.exists
    and
    "'uninstall' in ansible_run_tags"
  tags: [uninstall]
  ansible.builtin.meta: end_play
