# code: language=yaml
---
ansible_connection: ssh
ansible_ssh_user: "{{ users.provision }}"
ansible_ssh_private_key_file: "{{ ssh.path }}/{{ hostvars[hostvars[inventory_hostname]['bmc']]['ansible_ssh_prefix'] }}.ansible.key"

ip_address: "{{ network.profiles[profile].nodes[inventory_hostname] if network.profiles is defined else inventory_hostname }}"
tailscale:
  enabled: false
