# code: language=yaml
---
ansible_host: 0.0.0.0 # <-- Change this
ansible_connection: ssh
ansible_ssh_user: "{{ users.provision }}"
ansible_ssh_private_key_file: "{{ ssh.path }}/{{ hostvars[hostvars[inventory_hostname]['bmc']]['ansible_ssh_prefix'] }}.ansible.key"
