# code: language=ansible
---
- name: Enable Vault autocomplete
  become: true
  become_user: ubuntu
  tags: [config, autocomplete]
  ansible.builtin.command: vault -autocomplete-install
  args:
    creates: /etc/bash_completion.d/vault
