# code: language=ansible
---
- name: Configure sysctl
  tags: [sysctl]
  ansible.builtin.import_tasks:
    file: sysctl.yml

- name: Configure SELinux
  tags: [selinux]
  ansible.builtin.import_tasks:
    file: selinux.yml

- name: Configure htop
  tags: [htop]
  ansible.builtin.import_tasks:
    file: htop.yml

- name: Time Configuration
  tags: [timezone, ntp]
  ansible.builtin.import_tasks:
    file: time.yml

- name: Configure env_vars
  tags: [env_vars]
  ansible.builtin.import_tasks:
    file: env_vars.yml

- name: Install Packages
  tags: [packages]
  ansible.builtin.import_tasks:
    file: packages.yml
