# code: language=ansible
---
- name: Ensure Modules
  tags: [modules]
  become: true
  when: hostvars[inventory_hostname]['type'] | upper != "NVIDIA"
  block:
    - name: Load encryption modules immediately
      community.general.modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - dm_crypt

    - name: Ensure encyption modules at Boot
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/encryption.conf
        create: true
        line: "{{ item }}"
        state: present
        insertafter: EOF
        mode: "0644"
      loop:
        - dm_crypt

    - name: Ensure wireguard at Boot
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/wireguard.conf
        create: true
        line: "{{ item }}"
        state: present
        insertafter: EOF
        mode: "0644"
      loop:
        - wireguard
