# code: language=ansible
---
- name: Set MTU (RK1)
  tags: [network]
  when: hostvars[inventory_hostname]['type'] | upper == 'RK1'
  ansible.builtin.template:
    src: 01-eth0-mtu.yaml
    dest: /etc/netplan/01-eth0-mtu.yaml
    owner: root
    group: root
    mode: "0700"
  notify: "server : netplan-apply"

- name: Set MTU (Nvidia)
  tags: [network]
  when: hostvars[inventory_hostname]['type'] | upper == 'NVIDIA'
  ansible.builtin.shell:
    cmd: nmcli con modify Wired\ connection\ 1 802-3-ethernet.mtu 9000
    executable: /bin/bash
  changed_when: true
  notify: "server : reboot"
