# code: language=ansible
---
- name: Install Dependencies
  tags: [packages]
  ansible.builtin.apt:
    name:
      - jq
      - iptables
      - curl
      - iproute2
      - ethtool
      - socat
      - conntrack
      - git
      - git-lfs
      - acl
      - dnsutils
      - wireguard
      - ca-certificates
      - open-iscsi
      - iputils-ping
      - net-tools
      - arping
      - sudo
      - vim
      - nfs-common
    state: present
    update_cache: true
    cache_valid_time: 3600
    clean: true
    force_apt_get: true
    install_recommends: false

# FIx possible issue with missing cap_net_raw+p capability or setuid
- name: Fix Packages # noqa:command-instead-of-module
  tags: [packages]
  become: true
  ansible.builtin.command: apt-get reinstall iputils-ping
  changed_when: true
