# code: language=ansible
---
- name: Install the libselinux-python package
  tags: [selinux]
  ansible.builtin.apt:
    name:
      - policycoreutils
    state: present
    update_cache: true
    cache_valid_time: 3600
    install_recommends: false

- name: Check SELinux status
  tags: [selinux]
  ansible.builtin.command: sestatus
  register: selinux_status
  changed_when: false

- name: Install the libselinux-python package
  when: selinux_status.stdout.find("disabled") == -1
  tags: [selinux]
  ansible.builtin.apt:
    name:
      - auditd
      - python3-selinux
      - python3-semanage
      - selinux-policy-default
      - policycoreutils
    state: present
    update_cache: true
    cache_valid_time: 3600
    install_recommends: false

- name: Disable SELinux
  when: selinux_status.stdout.find("disabled") == -1
  tags: [selinux]
  throttle: 1
  ansible.posix.selinux:
    state: disabled
  notify: "server : reboot"

- name: Remove the libselinux-python package
  when: selinux_status.stdout.find("disabled") == -1
  tags: [selinux]
  ansible.builtin.apt:
    name:
      - auditd
      - python3-selinux
      - python3-semanage
      - selinux-policy-default
    state: absent
    update_cache: true
    cache_valid_time: 3600
    clean: true
    autoremove: true
    autoclean: true
    purge: true
