# code: language=ansible
---
- name: Update cache
  tags: [selinux]
  ansible.builtin.apt:
    update_cache: true

- name: Install the libselinux-python package
  tags: [selinux]
  ansible.builtin.apt:
    name:
      - auditd
      - python3-selinux
      - python3-semanage
      - selinux-policy-default
      - policycoreutils
    state: present
    cache_valid_time: 3600
    install_recommends: false

- name: Disable SELinux
  tags: [selinux]
  throttle: 1
  ansible.posix.selinux:
    state: disabled
  notify: "server : reboot"

- name: Remove the libselinux-python package
  tags: [selinux]
  ansible.builtin.apt:
    name:
      - auditd
      - python3-selinux
      - python3-semanage
      - selinux-policy-default
      - policycoreutils
    state: absent
    cache_valid_time: 3600
    clean: true
    autoremove: true
    autoclean: true
    purge: true
