- name: Unmount Node NVMe
  delegate_to: "{{ hostvars[inventory_hostname]['bmc'] }}"
  ansible.builtin.raw: umount -f /mnt/node || true
  changed_when: true

- name: Disable MSD (Mass Storage Driver)
  delegate_to: localhost
  ansible.builtin.raw: "tpi --host {{ bmc_host }} --user {{ bmc_user }} --password {{ bmc_pass }} advanced normal -n {{ node_slot }}"
  changed_when: true
  vars:
    node_slot: "{{ hostvars[inventory_hostname]['slot'] }}"
    bmc_host: "{{ hostvars[hostvars[inventory_hostname]['bmc']]['ansible_host'] }}"
    bmc_user: "{{ hostvars[hostvars[inventory_hostname]['bmc']]['ansible_ssh_user'] }}"
    bmc_pass: "{{ hostvars[hostvars[inventory_hostname]['bmc']]['ansible_ssh_pass'] }}"

- name: TPI Client Wait
  ansible.builtin.pause:
    seconds: 1

- name: Power Off Node
  ansible.builtin.import_role:
    name: tpi
    tasks_from: power-off.yml
