# code: language=ansible
---
- name: Unmount NVMe {{ inventory_hostname }}/cloud # noqa: name[template]
  delegate_to: "{{ hostvars[inventory_hostname]['bmc'] }}"
  ansible.builtin.raw: umount -f /mnt/node/cloud || true
  changed_when: true

- name: Unmount NVMe {{ inventory_hostname }}/root # noqa: name[template]
  delegate_to: "{{ hostvars[inventory_hostname]['bmc'] }}"
  ansible.builtin.raw: umount -f /mnt/node/root || true
  changed_when: true

- name: Disable MSD (Mass Storage Driver)
  delegate_to: localhost
  ansible.builtin.raw: |
    tpi --host {{ bmc_host }} --user {{ bmc_user }} --password {{ bmc_pass }} advanced normal -n {{ node_slot }}
    tpi --host {{ bmc_host }} --user {{ bmc_user }} --password {{ bmc_pass }} power off -n {{ node_slot }}
  changed_when: true
  vars:
    node_slot: "{{ hostvars[inventory_hostname]['slot'] }}"
    bmc_host: "{{ hostvars[hostvars[inventory_hostname]['bmc']]['ansible_ssh_host'] }}"
    bmc_user: "{{ hostvars[hostvars[inventory_hostname]['bmc']]['ansible_ssh_user'] }}"
    bmc_pass: "{{ hostvars[hostvars[inventory_hostname]['bmc']]['ansible_ssh_pass'] }}"
