---
- name: Power Off {{ inventory_hostname }} # noqa command-instead-of-shell
  delegate_to: localhost
  ansible.builtin.shell: "tpi --host {{ bmc_host }} --user {{ bmc_user }} --password {{ bmc_pass }} power off -n {{ node_slot }}"
  changed_when: true
  vars:
    node_slot: "{{ hostvars[inventory_hostname]['slot'] }}"
    bmc_host: "{{ hostvars[hostvars[inventory_hostname]['bmc']]['ansible_host'] }}"
    bmc_user: "{{ hostvars[hostvars[inventory_hostname]['bmc']]['ansible_ssh_user'] }}"
    bmc_pass: "{{ hostvars[hostvars[inventory_hostname]['bmc']]['ansible_ssh_pass'] }}"
