# SPDX-License-Identifier: MIT-0
---
- name: TPI Client
  ansible.builtin.import_role:
    name: tpi
    tasks_from: client-install.yml

- name: Clear remote-image Marker
  delegate_to: localhost
  when: flash_node | bool and flash_sdcard | bool
  ansible.builtin.file:
    path: "{{ flash.image.path.local }}/remote_image_exists"
    state: absent

- name: Create Local Directory
  delegate_to: localhost
  when: flash_node | bool
  ansible.builtin.file:
    path: "{{ flash.image.path.local }}"
    state: directory
    mode: "0755"

- name: Flash Nodes
  when: >
    inventory_hostname in groups['nodes'] and
    inventory_hostname == hostvars[hostname].inventory_hostname and
    ansible_limit | default('nodes,!tpi')
  ansible.builtin.include_tasks: tasks/node.yml
  with_items: "{{ groups['nodes'] }}"
  loop_control:
    loop_var: hostname
