# code: language=ansible
---
- name: Flash DISABLED
  when: not flash_node|bool
  ansible.builtin.debug:
    msg: "Flash: DISABLED; use '-e flash_node=true' to enable flashing of nodes"

- name: Clear remote-image Marker
  delegate_to: localhost
  when: flash_node | bool and flash_sdcard | bool
  ansible.builtin.file:
    path: "{{ flash.image.path.local }}/remote_image_exists"
    state: absent

- name: Create Local Directory
  delegate_to: localhost
  when: flash_node | bool
  ansible.builtin.file:
    path: "{{ flash.image.path.local }}"
    state: directory
    mode: "0755"

- name: Flash Nodes
  when: >
    flash_node | bool
    and
    (
      inventory_hostname in groups['nodes'] and
      inventory_hostname == hostvars[hostname].inventory_hostname and
      ansible_limit | default('nodes,!tpi')
    )
  ansible.builtin.include_tasks: tasks/node.yml
  with_items: "{{ groups['nodes'] }}"
  loop_control:
    loop_var: hostname
