# code: language=yaml
---
ssh:
  bitsize: 4096
  path: ~/.ssh/tpi

users:
  default: ubuntu
  provision: ansible

datetime:
  timezone: Etc/UTC
  ntp:
    servers: [pool.ntp.org]
    fallback:
      - ntp.ubuntu.com
      - time.google.com
