# code: language=yaml
---
ssh:
  bitsize: 4096
  path: ~/.ssh/tpi

users:
  default: ubuntu
  provision: ansible

datetime:
  timezone: Etc/UTC
  ntp:
    servers: [pool.ntp.org]
    fallback:
      - ntp.ubuntu.com
      - time.google.com

#
# Network configuration
#
# This is a template for the network configuration.
# The full schema can be found at: roles/network/vars/schema.yml
network:
  static: false

k3s:
  profile: academy # Change this to 'production' when switching to production

longhorn:
  enable_recurring_jobs: true # Enable based on profile needs
