# code: language=ansible
---
- name: Docker {{ item.user }} Config Exists? # noqa: name[template]
  tags: [docker, config]
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ inventory_dir }}/../config/docker/config.{{ item.user }}.json"
  register: docker_config
  changed_when: false

- name: Ensure {{ item.home }}/.docker # noqa: name[template]
  tags: [docker, config]
  when: docker_config.stat.exists | bool
  become: true
  ansible.builtin.file:
    path: "{{ item.home }}/.docker"
    state: directory
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: "0755"

- name: Install Docker Auth Config
  when: docker_config.stat.exists | bool
  tags: [docker, config]
  become: true
  ansible.builtin.copy:
    src: "{{ inventory_dir }}/../config/docker/config.{{ item.user }}.json"
    dest: "{{ item.home }}/.docker/config.json"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: "0600"
