# code: language=ansible
---
- name: Ensure Docker certs.d exists
  tags: [docker, config]
  become: true
  ansible.builtin.file:
    path: /etc/docker/certs.d
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"

- name: Check CA Exists
  when: docker.buildkitd.registries | length > 0
  tags: [docker, config]
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ inventory_dir }}/config/docker/{{ item.name }}/{{ item.ca }}"
  loop: "{{ docker.buildkitd.registries }}"
  register: docker_registries_ca

- name: Ensure Docker certs.d exists
  when: >
    docker.buildkitd.registries | length > 0 
    and 
    docker_registries_ca.results | map(attribute='stat.exists') | list
  tags: [docker, config]
  become: true
  ansible.builtin.file:
    path: "/etc/docker/certs.d/{{ item.name }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  loop: "{{ docker.buildkitd.registries }}"

- name: Copy CA Certs
  when: >
    docker.buildkitd.registries | length > 0 
    and 
    docker_registries_ca.results | map(attribute='stat.exists') | list
  tags: [docker, config]
  ansible.builtin.copy:
    src: "{{ inventory_dir }}/config/docker/{{ item.name }}/{{ item.ca }}"
    dest: "/etc/docker/certs.d/{{ item.name }}/ca.crt"
    owner: "root"
    group: "root"
    mode: "0644"
  loop: "{{ docker.buildkitd.registries }}"

- name: Copy buildkitd config
  tags: [docker, config]
  when: >
    docker.buildkitd.registries | length > 0 
    and 
    docker_registries_ca.results | map(attribute='stat.exists') | list
  ansible.builtin.template:
    src: buildkitd.toml
    dest: /etc/buildkitd.toml
    owner: root
    group: root
    mode: "0644"
  notify: "docker : restart"
