# code: language=ansible
---
- name: Docker Config Exists?
  tags: [docker, config]
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ inventory_dir }}/../config/docker/config.json"
  register: docker_config
  changed_when: false

- name: Copy Docker Config
  when: docker_config.stat.exists | bool
  tags: [docker, config]
  become: true
  ansible.builtin.copy:
    src: "{{ inventory_dir }}/../config/docker/config.json"
    dest: /etc/docker/config.json
    owner: root
    group: root
    mode: "0600"
