# code: language=ansible
---
- name: Package Check
  tags: [docker]
  ansible.builtin.package_facts:
    manager: apt

- name: Configure Docker Repository
  when: "'docker-ce' not in ansible_facts.packages"
  tags: [docker]
  block:
    - name: Remove Conflicting Packages
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - docker-compose-v2
          - podman-docker
          - containerd
          - runc
        state: absent
        cache_valid_time: 3600 # Cache valid for 1 hour to avoid repeated updates
        purge: true
        force_apt_get: true

    - name: Install required packages for Docker
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Docker GPG Key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker-keyring.gpg
        mode: "0755"

    - name: De-Armor Docker GPG Key
      ansible.builtin.command: "gpg --yes -o /usr/share/keyrings/docker-keyring.gpg --dearmor /tmp/docker-keyring.gpg"
      changed_when: true
      no_log: true

    - name: Get OS architecture
      ansible.builtin.command: dpkg --print-architecture
      changed_when: false
      register: os_arch

    - name: Docker Repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ os_arch.stdout }} signed-by=/usr/share/keyrings/docker-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        update_cache: true
        state: present

    - name: Delete download
      ansible.builtin.file:
        path: /tmp/docker-keyring.gpg
        state: absent

    - name: Install Docker CE
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true
        install_recommends: true

- name: Ensure Docker service is enabled and running
  tags: [docker]
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started

- name: Add users to the Docker group
  tags: [docker]
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop:
    - ubuntu

- name: Set docker socket group and permissions
  tags: [docker]
  ansible.builtin.file:
    path: /var/run/docker.sock
    owner: root
    group: docker
    mode: "0770"

- name: Enable docker qemu
  tags: [docker]
  ansible.builtin.include_tasks:
    file: qemu.yml

- name: Configure Nvidia Runtime
  when: hostvars[inventory_hostname]['type'] | upper == 'NVIDIA'
  tags: [docker, nvidia]
  ansible.builtin.include_tasks:
    file: nvidia.yml

- name: Configure Docker
  tags: [docker, config]
  ansible.builtin.include_tasks:
    file: config.yml

- name: Configure Authentication
  tags: [docker, config]
  ansible.builtin.include_tasks:
    file: auth.yml
  loop:
    - user: ubuntu
      home: /home/ubuntu
    - user: root
      home: /root

- name: Configure Buildkitd
  tags: [docker, config]
  ansible.builtin.include_tasks:
    file: buildkitd.yml
