# code: language=ansible
---
- name: Package Check
  tags: [docker]
  ansible.builtin.package_facts:
    manager: apt

- name: Configure qemu package
  when: "'qemu' not in ansible_facts.packages"
  tags: [docker]
  become: true
  block:
    - name: Install qemu packages
      ansible.builtin.apt:
        name:
          - binfmt-support
          - qemu-user-static
        state: present
        cache_valid_time: 3600

- name: Register Architectures
  tags: [docker]
  become: true
  ansible.builtin.shell:
    cmd: docker run --privileged --rm tonistiigi/binfmt --install all
    executable: /bin/bash
  changed_when: true
  notify: "docker : restart"
