# code: language=ansible
---
- name: Get Helm
  tags: [helm]
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: "/tmp/get_helm.sh"
    mode: "0755"
  changed_when: true

- name: Get Helm (Localhost)
  tags: [helm]
  delegate_to: localhost
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: "/tmp/get_helm.sh"
    mode: "0755"
  changed_when: true
  run_once: true

- name: Install Helm (Nodes)
  tags: [helm]
  become: true
  ansible.builtin.command:
    cmd: "/tmp/get_helm.sh"
  args:
    creates: /usr/local/bin/helm
  changed_when: true

- name: Install Helm (Localhost)
  delegate_to: localhost
  tags: [helm]
  become: true
  ansible.builtin.command:
    cmd: "/tmp/get_helm.sh"
  args:
    creates: /usr/local/bin/helm
  changed_when: true
  run_once: true
