# code: language=ansible
---
- name: Set Cluster Init Node
  tags: [kube-vip]
  ansible.builtin.set_fact:
    is_cluster_init_node: "{{ inventory_hostname == k3s.profiles[profile].cluster.init }}"

- name: Deploy kube-vip RBAC
  when: is_cluster_init_node
  tags: [kube-vip]
  become: true
  ansible.builtin.template:
    src: kube-vip/rbac.yml
    dest: /var/lib/rancher/k3s/server/manifests/kube-vip-rbac.yml
    mode: "0644"
  run_once: true

- name: Get kube-vip version # noqa: command-instead-of-module risky-shell-pipe
  delegate_to: localhost
  tags: [install, kube-vip]
  ansible.builtin.shell:
    cmd: curl -sL https://api.github.com/repos/kube-vip/kube-vip/releases | jq -r ".[0].name"
  register: kube_vip_version_raw
  changed_when: false
  run_once: true

- name: Set kube-vip version
  tags: [install, kube-vip]
  ansible.builtin.set_fact:
    kube_vip_version: "{{ kube_vip_version_raw.stdout_lines[0] }}"

- name: Deploy kube-vip Daemonset
  tags: [install, kube-vip]
  become: true
  ansible.builtin.template:
    src: kube-vip/kube-vip.yml.j2
    dest: /var/lib/rancher/k3s/server/manifests/kube-vip.yml
    mode: "0644"
  run_once: true

- name: Get kube-vip-cloud-provider version # noqa: command-instead-of-module risky-shell-pipe
  delegate_to: localhost
  tags: [install, kube-vip]
  ansible.builtin.shell:
    cmd: curl -sL https://api.github.com/repos/kube-vip/kube-vip-cloud-provider/releases | jq -r ".[0].name"
  register: kube_vip_cloud_provider_version_raw
  changed_when: false
  run_once: true

- name: Set kube-vip-cloud-provider version
  tags: [install, kube-vip]
  ansible.builtin.set_fact:
    kube_vip_cloud_provider_version: "{{ kube_vip_cloud_provider_version_raw.stdout_lines[0] }}"

- name: Configure kube-vip-cloud-provider
  tags: [install, kube-vip]
  become: true
  ansible.builtin.template:
    src: kube-vip/kubevip-configmap.yml.j2
    dest: /var/lib/rancher/k3s/server/manifests/kubevip-configmap.yml
    mode: "0644"
  changed_when: true
  run_once: true

- name: Deploy kube-vip-cloud-provider
  tags: [install, kube-vip]
  become: true
  ansible.builtin.template:
    src: kube-vip/kube-vip-cloud-provider.yml.j2
    dest: /var/lib/rancher/k3s/server/manifests/kube-vip-cloud-provider.yml
    mode: "0644"
  changed_when: true
  run_once: true
