# code: language=ansible
---
- name: "Set Cluster Init Node"
  tags: [install, kubeconfig]
  ansible.builtin.set_fact:
    is_cluster_init_node: "{{ inventory_hostname == k3s.profiles[profile].cluster.init }}"

- name: Find matching zone for local_ip
  tags: [install, kubeconfig]
  ansible.builtin.set_fact:
    local_ip: "{{ item.value.nodes[inventory_hostname] }}"
    matched_zone: "{{ item.key }}"
  loop: "{{ network.zones | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - item.value.profile == profile
    - inventory_hostname in item.value.nodes
  register: matched_zones

- name: Read kubeconfig
  when: is_cluster_init_node
  tags: [install, kubeconfig]
  ansible.builtin.command:
    cmd: cat /etc/rancher/k3s/k3s.yaml
  become: true
  register: kube_config_raw
  changed_when: false
  run_once: true

- name: Set Kube Config
  tags: [install, kubeconfig]
  ansible.builtin.set_fact:
    kube_config: "{{ kube_config_raw.stdout | regex_replace('127.0.0.1', k3s.profiles[profile].master.vip) }}"

- name: Create Directory .kube
  tags: [install, kubeconfig]
  become: true
  become_user: ubuntu
  ansible.builtin.file:
    path: "$HOME/.kube"
    state: directory
    mode: "0755"

- name: Write kubeconfig to $HOME/.kube/config
  tags: [install, kubeconfig]
  become: true
  become_user: ubuntu
  ansible.builtin.copy:
    content: "{{ kube_config }}"
    dest: "$HOME/.kube/config"
    mode: "0600"

- name: Create Directory .kube
  tags: [install, kubeconfig]
  delegate_to: localhost
  ansible.builtin.file:
    path: "/home/vscode/.kube"
    state: directory
    mode: "0755"
  run_once: true

- name: Write kubeconfig to $HOME/.kube/config
  delegate_to: localhost
  tags: [install, kubeconfig]
  ansible.builtin.copy:
    content: "{{ kube_config }}"
    dest: "/home/vscode/.kube/config"
    mode: "0600"
  run_once: true
