# code: language=ansible
# roles/k3s/tasks/shared/longhorn.yml
---
- name: Label node for Longhorn storage
  ansible.builtin.shell:
    cmd: kubectl label node $(hostname) longhorn-node=true --overwrite
  become: true
  changed_when: true
  failed_when: false

- name: "Create Longhorn data directory /data/{{ profile }}"
  become: true
  ansible.builtin.file:
    path: "/data/{{ profile }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: "Install Longhorn via Helm"
  become: true
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    create_namespace: true
    values_files:
      - roles/k3s/templates/longhorn-values.yaml.j2

- name: "Deploy Longhorn recurring job policy"
  become: true
  vars:
    recurring_jobs: "{{ k3s.profiles[profile].longhorn.recurring_jobs }}"
  kubernetes.core.k8s:
    state: present
    namespace: longhorn-system
    definition: "{{ lookup('template', 'longhorn-recurring-job.yaml.j2') | from_yaml }}"
