# code: language=ansible
# roles/k3s/tasks/shared/token.yml
---
- name: Check K3s Token Exists
  tags: [install, repair]
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.tpi/k3s.{{ profile }}.token"
  register: k3s_token_stat

- name: Generate K3s token
  when: not k3s_token_stat.stat.exists
  tags: [install, repair]
  delegate_to: localhost
  ansible.builtin.command: "uuidgen"
  register: k3s_token_gen
  changed_when: false

- name: Save Token (~/.tpi/k3s.{{ profile }}.token) # noqa: name[template]
  when: not k3s_token_stat.stat.exists
  tags: [install, repair]
  delegate_to: localhost
  ansible.builtin.copy:
    content: "{{ k3s_token_gen.stdout }}"
    dest: "{{ lookup('env', 'HOME') }}/.tpi/k3s.{{ profile }}.token"
    mode: "0600"

- name: Load K3s token
  tags: [install, repair]
  delegate_to: localhost
  ansible.builtin.slurp:
    src: "{{ lookup('env', 'HOME') }}/.tpi/k3s.{{ profile }}.token"
  register: k3s_token_file

- name: Set K3s token
  tags: [install, repair]
  ansible.builtin.set_fact:
    k3s_token: "{{ k3s_token_file.content | b64decode }}"
