# code: language=yaml
# roles/k3s/defaults/main.yml
---
k3s:
  profile: k3s
  cluster_init_node: node1
  version: v1.28.5+k3s1
  config_dir: /etc/rancher/k3s
  data_dir: /var/lib/rancher/k3s
  disable:
    - traefik
  args:
    server: []
    agent: []
  profiles:
    academy:
      longhorn:
        storage_path: /data/academy
        backup_target: nfs://nas.tailscale:/mnt/backups/academy
        enable_recurring_jobs: true
      tailscale:
        enable_subnet_routes: true
        enable_magic_dns: true
        tags:
          - tag:academy
    production:
      longhorn:
        storage_path: /data/global
        backup_target: nfs://nas.tailscale:/mnt/backups/global
        enable_recurring_jobs: true
      tailscale:
        enable_subnet_routes: true
        enable_magic_dns: true
        tags:
          - tag:production
