# code: language=yaml
# roles/k3s/defaults/main.yml
---
k3s:
  version: v1.28.5+k3s1
  config_dir: /etc/rancher/k3s
  data_dir: /var/lib/rancher/k3s
  disable:
    - traefik
    - local-storage
    - servicelb
  args:
    server:
      - --write-kubeconfig-mode 644
      - --disable-cloud-controller
    agent:
      - --write-kubeconfig-mode 644
  profiles:
    k3s:
      longhorn:
        storage_path: /data/global
        backup_target: nfs://nas.tailscale:/mnt/backups/global
        recurring_jobs: true
    academy:
      longhorn:
        storage_path: /data/academy
        backup_target: nfs://nas.tailscale:/mnt/backups/academy
        recurring_jobs: true
