# code: language=yaml
# roles/k3s/defaults/main.yml
---
k3s:
  version: v1.32.5+k3s1
  config_dir: /etc/rancher/k3s
  data_dir: /var/lib/rancher/k3s
  disable:
    - traefik
    - local-storage
    - servicelb
  args:
    server:
      - --write-kubeconfig-mode 644
      - --disable-cloud-controller
      - --kube-apiserver-arg=feature-gates=InPlacePodVerticalScaling=true
      - --kube-apiserver-arg=anonymous-auth=true
      - --kube-controller-manager-arg=feature-gates=InPlacePodVerticalScaling=true
      - --kube-controller-manager-arg=bind-address=0.0.0.0
      - --kube-scheduler-arg=feature-gates=InPlacePodVerticalScaling=true
      - --kube-scheduler-arg=bind-address=0.0.0.0
      - --kubelet-arg=feature-gates=InPlacePodVerticalScaling=true
      - --kube-proxy-arg=feature-gates=InPlacePodVerticalScaling=true
      - --etcd-expose-metrics=true
    agent:
      - --kubelet-arg=feature-gates=InPlacePodVerticalScaling=true
      - --kube-proxy-arg=feature-gates=InPlacePodVerticalScaling=true
  profiles:
    k3s:
      longhorn:
        storage_path: /data/shared
        backup_target: nfs://nas.tailscale:/mnt/backups/global
        recurring_jobs: true
    lab:
      longhorn:
        storage_path: /data/local
        backup_target: nfs://nas.tailscale:/mnt/backups/lab
        recurring_jobs: true
