---
- name: Install TPI CLI
  hosts: localhost
  gather_facts: true
  roles:
    - tpi-cli

- name: Flash Nodes
  hosts: "{{ ansible_limit | default('nodes,!tpi') }}"
  gather_facts: false
  tags: flash
  roles:
    - flash
