# code: language=ansible
---
- name: Requirements
  hosts: "{{ ansible_limit | default('nodes,!tpi') }}"
  gather_facts: false
  tags: [setup]
  serial: 1
  tasks:
    - name: Install TPI Client
      delegate_to: localhost
      ansible.builtin.import_role:
        name: tpi
        tasks_from: client-install.yml

- name: Flash Nodes
  hosts: "{{ ansible_limit | default('nodes,!tpi') }}"
  gather_facts: false
  tags: [flash]
  roles:
    - flash
