# code: language=ansible
---
- name: SSH Bootstrap
  ansible.builtin.import_playbook: ssh.yml

- name: Provision
  hosts: "{{ ansible_limit | default('nodes') }}"
  gather_facts: true
  tags: [provision]
  become: true
  roles:
    - role: server
    - role: upgrade
    - role: network

- name: SSH
  ansible.builtin.import_playbook: ssh.yml

- name: Provision
  hosts: "{{ ansible_limit | default('nodes') }}"
  gather_facts: true
  tags: [provision]
  become: true
  roles:
    - role: hosts
    - role: sata
    - role: nfs

- name: Reboot
  ansible.builtin.import_playbook: reboot.yml

- name: K3s
  hosts: "{{ ansible_limit | default('nodes') }}"
  gather_facts: true
  tags: [k3s, uninstall]
  become: true
  roles:
    - role: k3s
