# code: language=ansible
---
- name: Switch Network Nodes
  hosts: "{{ ansible_limit | default('!tpi') }}"
  become: true
  gather_facts: false
  tasks:
    - name: Gather Facts
      when: inventory_hostname not in groups['tpi']
      ansible.builtin.setup:

    - name: Switch Network Nodes
      when: inventory_hostname not in groups['tpi']
      ansible.builtin.import_role:
        name: network

- name: Switch Network BMC
  hosts: "{{ ansible_limit | default('tpi') }}"
  gather_facts: false
  tasks:
    - name: Set hostname
      when: inventory_hostname in groups['tpi']
      ansible.builtin.import_role:
        name: tpi
        tasks_from: hostname.yml
      vars:
        ansible_host: "{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}"

    - name: Set BMC Network
      when: inventory_hostname in groups['tpi']
      tags: [network]
      ansible.builtin.import_role:
        name: tpi
        tasks_from: network.yml
      vars:
        ansible_host: "{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}"
