# code: language=ansible
---
# This playbook is to provision a Nvidia Node
- name: Server Configuration
  hosts: "{{ ansible_limit | default('nodes,!tpi') }}"
  gather_facts: true
  become: true
  tags: [server]
  roles:
    - server

- name: Install Container Runtime
  hosts: "{{ ansible_limit | default('nodes,!tpi') }}"
  gather_facts: true
  tags: [docker, podman]
  become: true
  tasks:
    - name: Install / Configure Docker
      tags: [docker]
      when: container_runtime | lower == 'docker'
      ansible.builtin.import_role:
        name: docker
        tasks_from: main.yml

    - name: Install / Configure Podman
      tags: [podman]
      when: container_runtime | lower == 'podman'
      ansible.builtin.debug:
        msg: "Podman is not yet supported"
