# code: language=ansible
---
- name: Power Off
  hosts: "{{ ansible_limit|default('nodes,!bmc') }}"
  gather_facts: false
  tasks:
    - name: Power Off Node
      delegate_to: localhost
      ansible.builtin.import_role:
        name: bmc
        tasks_from: power-off.yml
