# code: language=ansible
---
- name: Power On
  hosts: "{{ ansible_limit|default('nodes,!tpi') }}"
  gather_facts: false
  tasks:
    - name: Power On Node
      ansible.builtin.import_role:
        name: tpi
        tasks_from: power-on.yml

    - name: Wait for Power On
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 22
        timeout: 5
      failed_when: false
