---
- name: Configure SSH
  hosts: tpi
  gather_facts: false
  serial: 1
  tags: [setup]
  roles:
    - ssh

- name: Update known_hosts
  hosts: "{{ ansible_limit | default('nodes, tpi') }}"
  gather_facts: false
  serial: 1
  tags: [known_hosts]
  tasks:
    - name: Add known_host {{ inventory_hostname }}
      when: inventory_hostname in groups.tpi
      vars:
        host: "{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}"
      ansible.builtin.include_role:
        name: ssh
        tasks_from: known_hosts.yml

    - name: Add known_host {{ inventory_hostname }}
      when: inventory_hostname in groups.nodes
      vars:
        host: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
      ansible.builtin.include_role:
        name: ssh
        tasks_from: known_hosts.yml

- name: Update config
  hosts: "{{ ansible_limit | default('nodes, tpi') }}"
  gather_facts: false
  serial: 1
  tags: [config]
  tasks:
    - name: Add tpi host {{ inventory_hostname }}
      when: inventory_hostname in groups.tpi
      vars:
        host: "{{ inventory_hostname }}"
        hostname: "{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}"
        username: "root"
        key: "{{ hostvars[inventory_hostname]['ansible_ssh_prefix'] }}.{{ inventory_hostname }}.key"
      ansible.builtin.include_role:
        name: ssh
        tasks_from: config.yml

    - name: Add node {{ inventory_hostname }}
      when: inventory_hostname in groups.nodes
      vars:
        host: "{{ inventory_hostname }}"
        hostname: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        username: "{{ users.default }}"
        key: "{{ hostvars[hostvars[inventory_hostname]['bmc']]['ansible_ssh_prefix'] }}.ubuntu.key"
      ansible.builtin.include_role:
        name: ssh
        tasks_from: config.yml
