---
- name: Configure SSH
  hosts: tpi
  gather_facts: false
  serial: 1
  tags: [setup]
  roles:
    - ssh

- name: Update known_hosts
  hosts: "{{ ansible_limit | default('nodes, tpi') }}"
  gather_facts: false
  serial: 1
  tags: [known_hosts]
  tasks:
    - name: Add known_host {{ inventory_hostname }}
      when: inventory_hostname in groups.tpi
      vars:
        host: "{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}"
      ansible.builtin.include_role:
        name: ssh
        tasks_from: known_hosts.yml

    - name: Add known_host {{ inventory_hostname }}
      when: inventory_hostname in groups.nodes
      vars:
        host: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
      ansible.builtin.include_role:
        name: ssh
        tasks_from: known_hosts.yml
