# code: language=ansible
---
- name: Install TPI CLI
  hosts: "{{ ansible_limit | default('localhost,nodes,!tpi') }}"
  gather_facts: true
  tasks:
    - name: Install TPI Client
      delegate_to: localhost
      tags: [tpi]
      ansible.builtin.import_role:
        name: tpi
        tasks_from: client-install.yml
