# code: language=ansible
---
- name: Copy hosts file
  when: inventory_hostname in groups['bmc']
  tags: [hosts]
  ansible.builtin.import_tasks:
    file: scp-send.yml
  vars:
    type: "template"
    src: hosts.j2
    dest: /etc/hosts
    mode: "0644"
    bmc_host: "{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}"
    bmc_user: "{{ hostvars[inventory_hostname]['ansible_ssh_user'] }}"
    bmc_pass: "{{ hostvars[inventory_hostname]['ansible_ssh_pass'] }}"
