# code: lang=ansible
---
- name: Set hostname
  when: inventory_hostname in groups['bmc']
  tags: [hostname]
  ansible.builtin.include_tasks:
    file: hostname.yml

- name: Set hosts
  when: inventory_hostname in groups['bmc']
  tags: [hosts]
  ansible.builtin.include_tasks:
    file: hosts.yml

- name: Set BMC Network
  when: inventory_hostname in groups['bmc']
  tags: [network]
  ansible.builtin.include_tasks:
    file: network.yml
#
# - name: Set BMC Network
#   when: inventory_hostname in groups['bmc']
#   tags: [routes]
#   ansible.builtin.include_tasks:
#     file: routes.yml
