# code: language=ansible
---
- name: Check Version
  when: inventory_hostname in groups['bmc']
  tags: [network]
  ansible.builtin.raw: |
    VERSION="$(tpi info|grep 'version' | grep -v 'build' | awk '{print $3}')"
    REQUIRED_VERSION="2.1.0"
    if [[ "$(echo -e "$VERSION\n$REQUIRED_VERSION" | sort -V | head -n1)" == "$REQUIRED_VERSION" ]]; then
      echo true
    else
      echo false
    fi
  register: bmc_version
  changed_when: false

- name: Is Bridge Version
  when: >
    bmc_version is defined
    and
    inventory_hostname in groups['bmc']
  tags: [network]
  ansible.builtin.set_fact:
    is_bridge_version: "{{ bmc_version.stdout_lines[0] | bool }}"
  changed_when: false

- name: Copy Network Configuration
  when: inventory_hostname in groups['bmc']
  tags: [network]
  ansible.builtin.include_tasks:
    file: scp-send.yml
  vars:
    type: "template"
    src: interfaces.j2
    dest: /etc/network/interfaces
    mode: "0644"
    bmc_host: "{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}"
    bmc_user: "{{ hostvars[inventory_hostname]['ansible_ssh_user'] }}"
    bmc_pass: "{{ hostvars[inventory_hostname]['ansible_ssh_pass'] }}"
  notify: network-restart
