# code: lang=ansible
---
- name: Create Persistent Scripts Dir
  when: inventory_hostname in groups['bmc']
  tags: [routes]
  ansible.builtin.raw: "mkdir -p /mnt/sdcard/scripts"
  changed_when: true

- name: Copy crond
  when: inventory_hostname in groups['bmc']
  tags: [routes]
  ansible.builtin.import_tasks:
    file: scp-send.yml
  vars:
    type: "file"
    src: S60crond
    dest: "/etc/init.d/S60crond"
    mode: "0755"
    bmc_host: "{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}"
    bmc_user: "{{ hostvars[inventory_hostname]['ansible_ssh_user'] }}"
    bmc_pass: "{{ hostvars[inventory_hostname]['ansible_ssh_pass'] }}"

- name: Restart crond
  when: inventory_hostname in groups['bmc']
  tags: [routes]
  ansible.builtin.raw: "/etc/init.d/S60crond restart"
  changed_when: true

- name: Copy Network Configuration
  when: inventory_hostname in groups['bmc']
  tags: [routes]
  ansible.builtin.import_tasks:
    file: scp-send.yml
  vars:
    type: "template"
    src: tailscale-routes.sh.j2
    dest: "/mnt/sdcard/scripts/tailscale-routes.sh"
    mode: "0755"
    bmc_host: "{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}"
    bmc_user: "{{ hostvars[inventory_hostname]['ansible_ssh_user'] }}"
    bmc_pass: "{{ hostvars[inventory_hostname]['ansible_ssh_pass'] }}"
